### ISSUE TITLE
Add explanation why zserio is more compact than protobuf

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio-protobuf-benchmarks#2]
The benchmark is good, but we should explain a bit in more detail why protobuf and zserio differ in size.

Here is good comparision (kudos to @dpelle for the summary):

Protobuf encodes more information for compatibility of encoder/decoder when proto file is changed. 
1) protobuf encodes each field ID (i.e. the = 1, = 2 in the following messages example, to preserve compatibility when adding new fields or reordering them in messages:
 message Road {
   int32 id = 1;
   string name = 2;
   ...
 }
These IDs have an encoding cost, which zserio does not pay. In zserio, it would merely be:
 struct Road {
   int32 id;
   string name;
 };
2) protobuf always encodes the field size, so that old decoders can skip field IDs which they do not know about, for forward/backward compatibility purpose. This has a cost which zserio does not pay.
3) in protobuf v3 (not v2), messages (non-singular fields) are always implicitly optional, which has an encoding cost for the the presence of the message. E.g.:
 syntax = proto3;
 struct Foo {
   Bar bar;  // bar message is implicitly optional in proto v3.
   ...
 }
This is again to help keeping compatibility between an encoder/decoder when proto file changes. In proto v2, it was not implicitly optional, but the guideline in proto v2 was to always use the optional keyword anyway, otherwise a field cannot be removed in future versions without breaking compatibility. zserio does not pay such compatibility price.
And regarding better compactness of zserio:
1) zserio can have fields for arbitrary bit size,  non-byte aligned, unlike protobuf which has fewer  possible types all byte aligned. And messages are not byte aligned in general (although explicit alignment is possible e..g align(32))
2) zserio has constraint expressions to indicate whether a field is encoded or not based on previously decoded information. The expression has 0 cost in encoding size since it's only present in the generated encoding/decoded C++ or Java code. In the following example, the box field is only encoded iff and expression following it is true, based on previously decoded info, which helps being compact:
 struct Foo {
   int8 type;
   BoundingBox box if type == 1;
   ...
 };
The encoding size of such struct in zserio would be only 1 byte (which may not be byte aligned) for the type field.
3) Arrays in zserio do not need to encode the size of the array. It's known in the generated encoding/decoding code, even for arrays of variable size as in the following example. When size is zero in particular, the array has 0 encoding cost:
 struct Foo {
   int8 num_items;
   Items list[num_items];
   ...
 }
In protobuf, this would be a repeated field, but the repeated field always has an encoding cost to encode its length as for every other fields in protobuf, to be able to skip it:
 message Foo {
   int8 num_items = 1;
   repeated Items list = 2;
 }

**Comment by mikir** [comment]
Thanks a lot for this comprehensive summary! I have added new [section](https://github.com/ndsev/zserio-protobuf-benchmarks/tree/master#why-is-zserio-more-compact-than-protobuf) to the README.md.

I am just not sure about point 3.  According to the [Protobuf Encoding Guide](https://protobuf.dev/programming-guides/encoding/#optional), it seems that optionals in Protobuf has zero encoding cost, they just leave out the record if it’s not present. For time being, I have not put this point to the README.md.
